### ISSUE TITLE
Query parameter: minimumAroundRadius

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-objc#23]
The parameter `minimumAroundRadius` can not be set in the Query

**Comment by clement-leprovost-algolia** [comment]
Already implemented in the `v3` branch.

**Comment by clement-leprovost-algolia** [comment]
Superseded by #25.

**Comment by sharad1404** [comment]
Our entire implementation is in obj-c. We have a need to set minimumAroundRadius, but we are stuck as we are not finding any docs to set this in obj-c. Can you please help guide us how to set this in obj-c.

**Comment by redox** [comment]
> Our entire implementation is in obj-c. We have a need to set minimumAroundRadius, but we are stuck as we are not finding any docs to set this in obj-c. Can you please help guide us how to set this in obj-c.

Hey @sharad1404,

you can still use the arbitrary query parameters available in our Objective-C API client:

```objective-c
ASQuery* query = [[ASQuery alloc] init];
[query set:@"minimumAroundRadius" value:@"100000"];
```

You may need to upgrade to the latest version however :)

**Comment by sharad1404** [comment]
Thanks Sylvain for the quick response. Will try this right away and let you
know if there are any questions.

thanks,
Sharad

**Comment by sharad1404** [comment]
One follow-up question re: implementation.

We tried the arbitrary query parameters  and it works fine. 
However - once we set the value - it persists for all future queries. Is there a way to reset it back for queries.

**Comment by clement-leprovost** [comment]
@sharad1404 Sorry, I am not sure to understand what you mean by "it persists for all future queries". :/

The `ASRemoteIndex` class does not persist the query between searches. However, if you are re-using the same `ASQuery` instance between searches, indeed the values will persist, but that's intentional. If you don't want this to happen, just create a new instance every time. Alternatively, you can call `-[ASQuery set:value:]` with a `nil` value, which will remove the corresponding extra parameter. (I wouldn't recommend this approach, however. Treating queries as immutable after they are constructed is in my opinion less error-prone.)
